//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Compra = new HashSet<Compra>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
